spring.datasource.url=jdbc:mysql://root:fCgxhcUhuwYTSGuoJpwEwSRlTKsrMzwR@switchback.proxy.rlwy.net:51963/railway
spring.datasource.username=root
spring.datasource.password=fCgxnchUhuWYTSGuoJpwEwSRlTKsrMzWR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true